# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesupporter',
            name='password',
            field=models.CharField(default=123, max_length=40),
            preserve_default=False,
        ),
    ]
