# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2011-01-01 00:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_user_registor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codesupporter',
            old_name='passwordnew',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user_registor',
            old_name='passwordnew',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='passwordnew',
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=datetime.datetime(2011, 1, 1, 0, 4, 41, 157721, tzinfo=utc), max_length=40),
            preserve_default=False,
        ),
    ]
