# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 01:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20110101_0006'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Registor_User',
        ),
    ]
