# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 02:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_registor_user_contact_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registor_user',
            old_name='contact_no',
            new_name='contact',
        ),
    ]
