# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 02:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20160723_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registor_user',
            name='contact',
        ),
    ]
