# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_registor_user_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='registor_user',
            name='user_contact',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
