# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_registor_user_contact_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100)),
                ('customer_id', models.CharField(max_length=50)),
                ('mobile_no', models.CharField(max_length=40)),
                ('email_no', models.CharField(max_length=20)),
                ('address', models.CharField(default='t', max_length=20)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.AlterField(
            model_name='registor_user',
            name='contact_no',
            field=models.CharField(default='t', max_length=20),
        ),
    ]
